# -*- mode: ruby -*-
# vi: set ft=ruby :

mgmtp1 = [8001, 9001]
mgmtp2 = [8002, 9002]
ctrlp = [8003, 9003]
bmp1 = [8004, 9004]
bmp2 = [8005, 9005]

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define "vqfx-pfe" do |vqfxpfe|
    vqfxpfe.vm.box = "juniper/vqfx10k-pfe"
    vqfxpfe.vm.guest = "openbsd"

    vqfxpfe.ssh.username = "root"
    vqfxpfe.ssh.password = "no"

    vqfxpfe.vm.provider :libvirt do |domain|
      domain.nic_model_type = "e1000"
      domain.disk_bus = 'ide'
      domain.cpus = 2
      domain.memory = 2048
    end

    vqfxpfe.vm.synced_folder '.', '/vagrant', disabled: true
    vqfxpfe.ssh.insert_key = false

    vqfxpfe.vm.network "private_network",
      :auto_config => false,
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_port => mgmtp1[1],
      :libvirt__tunnel_local_port => mgmtp1[0]
    vqfxpfe.vm.network "private_network",
      :auto_config => false,
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_port => mgmtp2[1],
      :libvirt__tunnel_local_port => mgmtp2[0]
  end

  config.vm.define "vqfx" do |vqfx|
    vqfx.vm.box = "juniper/vqfx10k-re"
    vqfx.vm.guest = "openbsd"

    vqfx.vm.synced_folder '.', '/vagrant', disabled: true

    vqfx.ssh.username = "root"
    vqfx.ssh.password = "Juniper"
    vqfx.ssh.shell = "cli"

    vqfx.vm.provider :libvirt do |domain|
      domain.disk_bus = 'ide'
      domain.nic_model_type = "e1000"
      domain.cpus = 2
      domain.memory = 2048
    end

    vqfx.vm.network "private_network",
      :auto_config => false,
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_port => mgmtp1[0],
      :libvirt__tunnel_local_port => mgmtp1[1]
    vqfx.vm.network "private_network",
      :auto_config => false,
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_port => mgmtp2[0],
      :libvirt__tunnel_local_port => mgmtp2[1]
    vqfx.vm.network "private_network",
      :auto_config => false,
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_port => ctrlp[0],
      :libvirt__tunnel_local_port => ctrlp[1]
    vqfx.vm.network "private_network",
      :auto_config => false,
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_port => bmp1[0],
      :libvirt__tunnel_local_port => bmp1[1]
    vqfx.vm.network "private_network",
      :auto_config => false,
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_port => bmp2[0],
      :libvirt__tunnel_local_port => bmp2[1]

    vqfx.vm.provision :ansible do |ansible|
      ansible.playbook = "vqfx.yml"
    end
  end

  config.vm.define "controller" do |controller|
    controller.vm.hostname = "devstack"
    controller.vm.box = "centos/7"

    controller.vm.provider :libvirt do |domain|
      domain.cpus = 2
      domain.memory = 4096
    end

    controller.vm.network "private_network",
      :auto_config => false,
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_port => ctrlp[1],
      :libvirt__tunnel_local_port => ctrlp[0]

    controller.vm.provision :ansible do |ansible|
      ansible.playbook = "controller.yml"
    end
  end

  config.vm.define "bm1" do |bm1|
    bm1.vm.hostname = "bm1"
    bm1.vm.box = "centos/7"

    bm1.vm.network "private_network",
      :auto_config => false,
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_port => bmp1[1],
      :libvirt__tunnel_local_port => bmp1[0]

  end

  config.vm.define "bm2" do |bm2|
    bm2.vm.hostname = "bm2"
    bm2.vm.box = "centos/7"

    bm2.vm.network "private_network",
      :auto_config => false,
      :libvirt__tunnel_type => "udp",
      :libvirt__tunnel_port => bmp2[1],
      :libvirt__tunnel_local_port => bmp2[0]

  end

end
